version: 0.2
phases:
  pre_build:
    commands:
      - TAG=$(aws codepipeline get-pipeline-state --name jeyvalue | grep -i pipelineExecutionId | awk '{print $2}' | tr -d \",- | head -n 1)
      - IMAGE_URI=601504529245.dkr.ecr.ap-south-1.amazonaws.com/keyvalue
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 601504529245.dkr.ecr.ap-south-1.amazonaws.com/keyvalue
  build:
    commands:
      - docker build -t 601504529245.dkr.ecr.ap-south-1.amazonaws.com/keyvalue .
      - docker tag 601504529245.dkr.ecr.ap-south-1.amazonaws.com/keyvalue 601504529245.dkr.ecr.ap-south-1.amazonaws.com/keyvalue:${TAG}
      - docker push 601504529245.dkr.ecr.ap-south-1.amazonaws.com/keyvalue
      - docker push 601504529245.dkr.ecr.ap-south-1.amazonaws.com/keyvalue:${TAG}
      - echo "Build Done"
  post_build:
    commands:
      - echo "Post Build Done"
